## day1 for DA (ndarry--2018/8/9)

In [6]:
import numpy as np
arr1=np.array([1,2,3,4])
print('数组：',arr1)

数组： [1 2 3 4]


In [9]:
arr2=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print('数组：\n',arr2)

数组：
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [12]:
print(arr2.shape)

(3, 4)


In [13]:
print(arr2.dtype)

int32


In [14]:
print(arr2.size)

12


In [15]:
print(arr2.itemsize)

4


In [17]:
arr2.shape=4,3
print('reset shape:',arr2)

reset shape: [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [18]:
arr3=np.arange(0,1,0.1)
print(arr3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [19]:
arr4=np.linspace(0,1,12)
print(arr4)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [21]:
arr5=np.logspace(0,2,20)
print(arr5)

[  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


In [22]:
arr6=np.zeros((2,3))
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
arr7=np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr8=np.diag([1,2,3,4])
print(arr8)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [28]:
arr9=np.ones((5,3))
print(arr9)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
