## day2 for DA(np matrix)

In [1]:
import numpy as np
matr1=np.mat('1 2 3;4 5 6;7 8 9')
matr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [2]:
matr2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matr2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
arr1=np.eye(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
arr2=3*arr1
arr2

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [13]:
arr3=np.bmat('arr1 arr2;arr1 arr2')
arr3

matrix([[1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.],
        [1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.]])

In [14]:
arr3.T

matrix([[1., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1.],
        [3., 0., 0., 3., 0., 0.],
        [0., 3., 0., 0., 3., 0.],
        [0., 0., 3., 0., 0., 3.]])

In [18]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x*y)
print(x^2)
print(x**y)

[5 7 9]
[ 4 10 18]
[3 0 1]
[  1  32 729]


In [19]:
x<y

array([ True,  True,  True])

In [20]:
x != y

array([ True,  True,  True])

In [21]:
np.all(x==y)

False

In [22]:
np.any(x==y)

False

In [3]:
import numpy as np
arr1=np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [4]:
arr1.shape

(4, 3)

In [5]:
arr2=np.array([1,2,3])
arr2

array([1, 2, 3])

In [6]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
arr3=np.array([1,2,3,4]).reshape(4,1)
arr3

array([[1],
       [2],
       [3],
       [4]])

In [8]:
arr1+arr3

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])