## day2 for DA ( ndarray)

In [1]:
import numpy as np
print(np.float64(32))

32.0


In [2]:
print(np.int8(32.0))

32


In [3]:
print(np.bool(32))

True


In [4]:
print(np.bool(0))

False


In [5]:
print(np.float(True))

1.0


In [12]:
np.float(False)

0.0

In [7]:
df = np.dtype([('name',np.str_,40),('numiteams',np.int64),('price',np.float64)])

In [8]:
print('数据类型：',df)

数据类型： [('name', '<U40'), ('numiteams', '<i8'), ('price', '<f8')]


In [11]:
df['name']

dtype('<U40')

In [14]:
arr1=np.array([('name','zhanghao','zhangyang'),('age',23,16)])
arr1

array([['name', 'zhanghao', 'zhangyang'],
       ['age', '23', '16']], dtype='<U9')

In [16]:
np.random.random(10)

array([0.74237121, 0.05011019, 0.34308239, 0.0104124 , 0.96045152,
       0.01363631, 0.60775641, 0.06985008, 0.15271861, 0.19706679])

In [18]:
np.random.rand(3,2)

array([[0.76216477, 0.58776199],
       [0.04631877, 0.50970079],
       [0.77953715, 0.59638624]])

In [19]:
np.random.randn(3,2)

array([[ 0.82516168, -0.3097942 ],
       [ 1.27228234,  0.21091607],
       [ 0.08197666,  0.78805231]])

In [20]:
np.random.randint(1,12,(3,4))

array([[ 9,  3,  6, 11],
       [ 7,  7,  9,  8],
       [ 6,  8,  2, 11]])

In [21]:
arr2=np.arange(10)

In [22]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2[1:3]

array([1, 2])

In [24]:
arr2[0]

0

In [26]:
arr2[1:-1:2]

array([1, 3, 5, 7])

In [27]:
arr2[-1:1:-3]

array([9, 6, 3])

In [28]:
arr3=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [29]:
arr3

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [31]:
arr3[0,2:4]

array([3, 4])

In [32]:
arr3[1:,2:]

array([[ 6,  7],
       [ 9, 10]])

In [33]:
arr4=np.arange(12)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr4.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
arr4.reshape(3,4).ndim

2

In [36]:
arr5=np.arange(12).reshape(3,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
arr5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
arr5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr5.flatten('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [41]:
arr6=np.arange(12).reshape(3,4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
arr7=arr6*3
arr7

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [44]:
np.hstack((arr6,arr7))

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

In [45]:
np.vstack((arr6,arr7))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [46]:
np.concatenate((arr6,arr7),axis=1)

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

In [47]:
np.concatenate((arr6,arr7),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [48]:
arr1=np.arange(16).reshape(4,4)

In [49]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.hsplit(arr1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.vsplit(arr1,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [53]:
np.split(arr1,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [54]:
np.split(arr1,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]